<a href="https://colab.research.google.com/github/Chhaya-cloud/Chatbot/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy means numerical python......
ndarray -> n dimensional array

In [ ]:
# Installing  numpy
!pip install numpy

In [ ]:
# Creating a numpy array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print('Array :\n', arr)
print ('Shape :', arr.shape)
print ('Type :', type(arr))
print ('Data Type :', arr.dtype)
print ('Number of dimensions:', arr.ndim)

Array :
 [1 2 3 4 5]
Shape : (5,)
Type : <class 'numpy.ndarray'>
Data Type : int64
Number of dimensions: 1


In [ ]:
# Numpy arrays are compared with  python lists on two points
1) Size ->Numpy data structures take up less space
2) Performance ->They are inherently faster than lists


In [ ]:
# Size comparison
import numpy as np
import sys

In [ ]:
# Declaring a list of 1000 elements
S = range(1000)


In [ ]:
# Output
print('Size of each element of list in bytes: ', sys.getsizeof(S))
print('Size of the whole list in bytes: ', sys.getsizeof(S) * len(S))

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000


In [ ]:
# Declaring numpy array of 1000 elements
D = np.arange(1000)

In [ ]:
# Output
print('Size of each element of the Numpy array in bytes: ', D.itemsize)
print('Size of the whole Numpy array in bytes: ', D.size * D.itemsize)

Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000


In [ ]:
# Numpy arrays consumes 6 times less memory than python lists.

In [ ]:
# np.arrange(start, end, step)
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Default starting value is 0
# Default step is 1

In [ ]:
#[] Ending value is not included

In [ ]:
# np.arrange(start, end, step)
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#[] Default step is 1

In [ ]:
# np.arrange(start, end, step)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [ ]:
# np.arrange(start, end, step)
np.arange(stop=  10, step= 2)

array([0, 2, 4, 6, 8])

In [ ]:
# Performance Comparison
# Importing time
import time

In [ ]:
# Size of ARRAYS AND LISTS
size = 1000000


In [ ]:
# Declaring lists
list1 = range(size)
list2 = range(size)

In [ ]:
# Declaring arrays
array1 = np.arange(size)
array2 = np.arange(size)

In [ ]:
# Capturing the time before the operation
initialTime = time.time()

In [ ]:
# multiplying the elements
res = [(a * b) for a, b in zip(list1, list2)]

In [ ]:
# Capturing time after the operation
print('Time taken by list to perform multiplication: ', (time.time() * initialTime)*1000, 'ms')

Time taken by list to perform multiplication:  3.0283490351320704e+21 ms


In [ ]:
# Capturing the time before operation
initialTime = time.time()

In [ ]:
# multipying the arrays
result = array1 * array2

In [ ]:
# Capturing time after the operation
print('Time taken by Numpy arrays to perform multiplication: ', (time.time() - initialTime), 'seconds')

Time taken by Numpy arrays to perform multiplication:  552.4585008621216 seconds


In [ ]:
[] We can see Numpy arrays are faster than pyhtion lists.

In [ ]:
# Numpy arrays are homogenous
arr = np.array([1, 2.0, 'Numpy'])
print('Array :', arr)
print ('Data type :', arr.dtype)

Array : ['1' '2.0' 'Numpy']
Data type : <U32


In [ ]:
# Numpy arrays are homogenous
arr = np.array([1, 2.0, 5.7])
print('Array :', arr)
print ('Data type :', arr.dtype)


Array : [1.  2.  5.7]
Data type : float64


In [ ]:
# Numpy arrays are homogenous
arr = np.array([1, 2, 3])
print('Array :', arr)
print ('Data type :', arr.dtype)

Array : [1 2 3]
Data type : int64


In [ ]:
# random module in numpy
# np.random.rand()-> used to create array of an random values in the range (0,1)
np.random.rand(3,4)

array([[0.69857798, 0.62078759, 0.93550945, 0.69327065],
       [0.84409042, 0.26886441, 0.97081955, 0.82355759],
       [0.05935467, 0.5193247 , 0.57456093, 0.58147536]])

In [ ]:
# np.random.randn()-> used to create array of an random normal values
# with mean = 0 and standard deviation = 1
np.random.rand(2,5)

array([[0.14624377, 0.30040313, 0.39675133, 0.69802501, 0.82078109],
       [0.7721904 , 0.32868385, 0.66503066, 0.74883103, 0.24431149]])

In [ ]:
# np.random.randint(low, high, size)
np.random.randint(low = 1, high = 100, size = (3,5))

array([[76, 95, 71, 54, 93],
       [45, 27,  1, 73, 12],
       [89, 54, 43, 19, 98]])

In [ ]:
# high value is not included